global:
 scrape_interval: 15s
 evaluation_interval: 15s


scrape_configs:
   - job_name: 'mysql'
     metrics_path: /metrics
     static_configs:
       - targets:
          - mysql:9187
   - job_name: 'mysql_exporter'
     scrape_interval: 5s
     static_configs:
       - targets:
          - mysql:9104
   - job_name: 'haproxy'
     metrics_path: /metrics
     static_configs:
       - targets:
          - haproxy:9300
   - job_name: 'node'
     metrics_path: /metrics
     static_configs:
      - targets:
         - haproxy:9100
         - mysql:9100
         - web:9100
   - job_name: 'nginx'
     metrics_path: /metrics
     static_configs:
      - targets:
         - web:9113
   - job_name: 'ssh'
     metrics_path: /probe
     static_configs:
      - targets:
         - web:9428
